[workspace]
members = ["quinn", "quinn-proto", "quinn-h3", "interop", "bench"]

[profile.bench]
debug = true

[profile.release]
debug = true

[patch.crates-io]
rustls = { git = "https://github.com/ctz/rustls", rev = "46c259bd8e28dcfca6c1934aabb58a0da0736cb7" }
