[package]
name = "quinn"
version = "0.4.0"
authors = ["Benjamin Saunders <ben.e.saunders@gmail.com>", "Dirkjan Ochtman <dirkjan@ochtman.nl>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/djc/quinn"
description = "QUIC transport protocol implementation for Tokio"
readme = "../README.md"
keywords = ["quic"]
categories = [ "network-programming", "asynchronous" ]
workspace = ".."
edition = "2018"

[package.metadata.docs.rs]
all-features = true

[badges]
codecov = { repository = "djc/quinn" }
maintenance = { status = "experimental" }
travis-ci = { repository = "djc/quinn" }

[dependencies]
bytes = "0.4.7"
ct-logs = "0.5"
err-derive = "0.1.5"
fnv = "1.0.6"
futures = { package = "futures-preview", version = "0.3.0-alpha.16" }
libc = "0.2.49"
mio = "0.6"
proto = { package = "quinn-proto", path = "../quinn-proto", version = "0.4.0" }
rand = "0.6"
rustls = { version = "0.15.2", features = ["quic"] }
slog = "2.1"
tokio-reactor = { git = "https://github.com/tokio-rs/tokio", rev = "1f08354c08a3c423048267f47d1a365ca6c1a1dc" }
tokio-io = { git = "https://github.com/tokio-rs/tokio", rev = "1f08354c08a3c423048267f47d1a365ca6c1a1dc" }
tokio-timer = { git = "https://github.com/tokio-rs/tokio", rev = "1f08354c08a3c423048267f47d1a365ca6c1a1dc" }
webpki = "0.19"
webpki-roots = "0.16"

[dev-dependencies]
crc = "1.8.1"
criterion = "0.2.10"
directories = "2.0.0"
failure = "0.1"
rand = "0.6.5"
rcgen = "0.3"
slog-term = "2"
structopt = "0.2.7"
tokio = "0.1.6"
tokio-current-thread = "0.1"
unwrap = "1.2.1"
url = "1.7"

[[example]]
name = "server"

[[example]]
name = "client"

[[example]]
name = "insecure_connection"
required-features = ["rustls/dangerous_configuration"]

[[bench]]
name = "bench"
harness = false
