[package]
name = "interop"
version = "0.1.0"
authors = ["Benjamin Saunders <ben.e.saunders@gmail.com>"]
edition = "2018"

[dependencies]
quinn = { path = "../quinn", version = "0.1.0" }
slog-term = "2"
structopt = "0.2.7"
tokio = "0.1.6"
tokio-current-thread = "0.1"
rustls = { git = "https://github.com/Ralith/rustls.git", rev = "b4b9b1b8e080129c418bddb2e110ee1780b16793", features = ["dangerous_configuration"] }
failure = "0.1"
slog = "2.2"
futures = "0.1.21"
webpki = "0.18"
