[package]
name = "interop"
version = "0.1.0"
authors = ["Benjamin Saunders <ben.e.saunders@gmail.com>", "Jean-Christophe BEGUE <begue.jc@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"
default-run = "main"
publish = false

[dependencies]
anyhow = "1.0.22"
bytes = "0.5.2"
futures = "0.3.8"
http = "0.2"
http-body = "0.3"
hyper = "0.13"
hyper-rustls = { git = "https://github.com/kwantam/hyper-rustls", rev = "1cf069878193" }
lazy_static = "1"
quinn = { path = "../quinn" }
quinn-h3 = { path = "../quinn-h3", features = ["interop-test-accessors"] }
quinn-proto = { path = "../quinn-proto" }
rustls = { git = "https://github.com/ctz/rustls", rev = "fee894f7e030", features = ["dangerous_configuration"] }
structopt = "0.3.0"
tokio = { version = "0.2.2", features = ["macros", "rt-core", "io-util"] }
tokio-rustls = { git = "https://github.com/kwantam/tokio-rustls", rev = "684cc546e754" }
tracing = "0.1.10"
tracing-subscriber = { version = "0.2.5", default-features = false, features = ["env-filter", "fmt", "ansi", "chrono"]}
tracing-futures = { version = "0.2.0", default-features = false, features = ["std-future"] }
webpki = "0.21"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "qif"
path = "src/qif.rs"
