[package]
name = "interop"
version = "0.1.0"
authors = ["Benjamin Saunders <ben.e.saunders@gmail.com>", "Jean-Christophe BEGUE <begue.jc@gmail.com>"]
edition = "2018"
default-run = "main"

[dependencies]
quinn = { path = "../quinn" }
#quinn-h3 = { path = "../quinn-h3" }
quinn-proto = { path = "../quinn-proto" }
slog-term = "2"
bytes = "0.4.7"
structopt = "0.3.0"
tokio = "0.2.0-alpha.5"
tokio-net = "0.2.0-alpha.5" # tokio doesn't reexport everything we use
rustls = { version = "0.16", features = ["dangerous_configuration"] }
failure = "0.1"
slog = "2.2"
futures = { package = "futures-preview", version = "0.3.0-alpha.18" }
webpki = "0.21"

[[bin]]
name = "main"
path = "src/main.rs"

# [[bin]]
# name = "qif"
# path = "src/qif.rs"
