[package]
name = "interop"
version = "0.1.0"
authors = ["Benjamin Saunders <ben.e.saunders@gmail.com>"]
edition = "2018"

[dependencies]
quinn = { path = "../quinn" }
quinn-h3 = { path = "../quinn-h3" }
quinn-proto = { path = "../quinn-proto" }
slog-term = "2"
bytes = "0.4.7"
structopt = "0.2.7"
tokio = "0.1.6"
tokio-current-thread = "0.1"
tokio-reactor = "0.1"
rustls = { version = "0.15", features = ["dangerous_configuration"] }
failure = "0.1"
slog = "2.2"
futures = "0.1.21"
webpki = "0.19"

[[bin]]
name = "qif"
path = "src/qif.rs"